### PR TITLE
In the case where AMD is used, Expose store to the global window object ...

### PR DESCRIPTION
**Pull request by raikoroje**
...so extensions (like store.overlfow.js) can extend it :)

### CODE REVIEW

**Comment by nbubna** [comment]
Looks like you are changing the behavior in a way past AMD users disagree with. While we consider the merits, your pull request should at least update the tests so they don't fail.

**Comment by raikoroje** [comment]
Thanks for the the response, I'll update the tests shortly.

**Comment by raikoroje** [comment]
P.s jQuery uses a similar approach to make it easily extensible. :)

**Comment by nbubna** [comment]
Well, if jQuery does it... :)

**Pull request merged**
