### PR TITLE
Add TypeScript declaration file

### PR DESCRIPTION
**Pull request by ahstro**
I took a shot at creating some TypeScript types for store2. I haven't put too much time into figuring out exactly how the library works, so there might be things that are not 100%.

I wasn't sure if this was desired, so I decided to create a PR with what I had and, if the response is positive, I could look into creating some unit tests.

### CODE REVIEW

**Comment by nbubna** [comment]
Yeah, typings would be great! I'm planning to use TypeScript on an upcoming project myself, so this will come in handy.

I've got a hectic day, so i may not be able to look at it carefully today, but it looks pretty decent at a glance. Though, i will say that the library is typically exported/imported as 'store', not 'store2'

**Comment by ahstro** [comment]
No problem, take your time :)

From what I understood of the source, the UMD global is called `store2`, so I went with that. It's probably possible to call it `store` locally but still make the UMD value typed though.

**Comment by nbubna** [comment]
It's only store2 for the AMD part of the UMD definition. I've mostly accepted patches for that part, as it is my least used/preferred module system.

All the documentation uses 'store', so i would prefer that.

**Comment by ahstro** [comment]
Yeah, I realized I missed those parts too, but I also don't know how to "repeat" an interface. I'll update the PR when I get a bit better at type declarations.

**Comment by nbubna** [comment]
I wasn't happy with the typings lack of coverage so i did some reading on TypeScript and updated it with what i hope is a more accurate and complete version. Please pull the latest version (2.5.3) and tell me if it works for you. Thanks!

**Comment by ahstro** [comment]
Doesn't really seem to be working at all I'm afraid. I think there might be some problem related to the `store` namespace and interface and what's exported how. Can't really dig deeper at the moment, sorry.

**Comment by nbubna** [comment]
Is there another library you use that provides typescript support (that works)? I'd like to see how others do it. And heck, what are you using to test this, for that matter?

**Comment by ahstro** [comment]
[momentjs](https://github.com/moment/moment/) has [their own type declarations](https://github.com/moment/moment/blob/develop/moment.d.ts) that should be fairly comprehensive. I'm running the TypeScript compiler on my project and it complains if I'm using store in a way that isn't allowed by the declarations file. I think there are some testing utilities specific to declaration files though. Check out [DefinitelyTyped](https://github.com/definitelytyped/definitelytyped), I think that'd be a good start to figure out how to write and test types properly :)

**Pull request merged**
