### PR TITLE
Fixes mismatched anonymous module bug with require.js

### LINKED ISSUE #15: Support AMD
If you are willing I could create a AMD integration as well.

### PR DESCRIPTION
**Pull request by Jamesking56**
Fixes #15

### CODE REVIEW

**Comment by Jamesking56** [comment]
To use, here is the config line you need for require.js:

````js
require.config({
    paths: {
        store2: 'bower_components/store2/dist/store2'
    }
});
````

**Comment by nbubna** [comment]
It would probably be best if you add a test for this also, to ensure it does not get reverted.

**Comment by tchak** [comment]
Because of this (and this.define passed in the closure) it is now broken with `ember-cli` and `ember-cli-node-assets`... I would provide a patch, but I don't understand the change... How is it supposed to work? Now it complains for not having a named `store2` amd module, which makes sens.

**Comment by nbubna** [comment]
I don't know, and i don't have time to figure this out. James King, can you chime in here? I'm so sick of these varying module systems.

**Comment by Jamesking56** [comment]
@tchak this patch should name the module as 'store2' (the same as the JS file). I don't know how ember works, maybe it's expecting a different name?

**Comment by tchak** [comment]
@Jamesking56 I should not have brought `ember` in here, it has nothing to do with the problem. `ember-cli` can work with either a standard `requirejs` named export or an anonymous one. Providing named exports is rather unusual in my experience. But if you want it to be a named export as `store2` I think the correct expression would be `define('store2', [], function () {})`. Your patch is to make it `define(['store2'], function () {})`. I am not an expert on `requirejs` but this means to me that it depends on `store2` which is undefined. I am not sure what is going on here and how it can work for you.

**Comment by tchak** [comment]
@nbubna I understand your pain. Sorry for the truble and thanks for your work.

**Comment by Jamesking56** [comment]
Well, I've tested this patch and it seems to work perfectly fine in my Marionette / Backbone SPA.

What happens when you try my fork in Ember?

**Comment by Jamesking56** [comment]
In fact, I'll edit my fork now and try your way. There's some articles online that suggest the way you're describing as being the more accepted and 'correct' way.

**Comment by Jamesking56** [comment]
Also @nbubna the existing AMD test should test for this.

**Comment by nbubna** [comment]
Any progress on this @Jamesking56 ? Should we change to the way @tchak recommends?

And "should test" as in "should already" or "should be made to"?

**Comment by Jamesking56** [comment]
I've made the change my in fork (in master) for @tchak to test, shall I create a new PR?

And what I mean is the AMD test should already cover testing this (it already exists in your repo)

**Comment by nbubna** [comment]
Yeah, go ahead and make the PR. I hope it works for @tchak , but if not, at least it appears to be the more accepted/correct/whatever way of doing it.

**Comment by nbubna** [comment]
Alright, i just went ahead and made the change. The AMD test passes, and i hope it helps. :)

**Comment by nbubna** [comment]
Oh, release version is 2.5.0

**Pull request merged**
